diahora:
    pattern:  /diahora/index
    defaults: { _controller: QQiRecordappBundle:Diahora:index }

diahora_show:
    pattern:  /diahora/{id}/show
    defaults: { _controller: QQiRecordappBundle:Diahora:show }

diahora_new:
    pattern:  /diahora/new
    defaults: { _controller: QQiRecordappBundle:Diahora:new }

diahora_create:
    pattern:  /diahora/create
    defaults: { _controller: QQiRecordappBundle:Diahora:create }
    requirements: { _method: post }

diahora_edit:
    pattern:  /diahora/{id}/edit
    defaults: { _controller: QQiRecordappBundle:Diahora:edit }

diahora_update:
    pattern:  /diahora/{id}/update
    defaults: { _controller: QQiRecordappBundle:Diahora:update }
    requirements: { _method: post }

diahora_delete:
    pattern:  /diahora/{id}/delete
    defaults: { _controller: QQiRecordappBundle:Diahora:delete }
    requirements: { _method: post }
