parameters:
    database_driver:   pdo_pgsql
    database_host:     localhost
    database_port:     5432
    database_name:     bad_role
    database_user:     bad
    database_password: bad

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            bad
