
#q_qi_recordapp:
#    resource: "@QQiRecordappBundle/Controller/"
#    type:     annotation
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_usuario:
    resource: "@QQiRecordappBundle/Resources/config/usuario_routing.yml"

_rol:
    resource: "@QQiRecordappBundle/Resources/config/rol_routing.yml"

_tarea:
    resource: "@QQiRecordappBundle/Resources/config/tarea_routing.yml"

_enlace:
    resource: "@QQiRecordappBundle/Resources/config/enlace_routing.yml"

_informe:
    resource: "@QQiRecordappBundle/Resources/config/informe_routing.yml"

_tipoactividad:
    resource: "@QQiRecordappBundle/Resources/config/routing/tipoactividad.yml"

_ciclo:
    resource: "@QQiRecordappBundle/Resources/config/routing/ciclo.yml"

_estados:
    resource: "@QQiRecordappBundle/Resources/config/routing/estados.yml"

_lugar:
    resource: "@QQiRecordappBundle/Resources/config/routing/lugar.yml"

_facultad:
    resource: "@QQiRecordappBundle/Resources/config/routing/facultad.yml"

_tipolugar:
    resource: "@QQiRecordappBundle/Resources/config/routing/tipolugar.yml"

_tipoactividad:
    resource: "@QQiRecordappBundle/Resources/config/routing/tipoactividad.yml"

_carrera:
    resource: "@QQiRecordappBundle/Resources/config/routing/carrera.yml"

_escuelas:
    resource: "@QQiRecordappBundle/Resources/config/routing/escuelas.yml"

_asignatura:
    resource: "@QQiRecordappBundle/Resources/config/routing/asignatura.yml"

_diahora:
    resource: "@QQiRecordappBundle/Resources/config/routing/diahora.yml"

_pensum:
    resource: "@QQiRecordappBundle/Resources/config/routing/pensum.yml"

_horario:
    resource: "@QQiRecordappBundle/Resources/config/routing/horario.yml"

_comun:
    resource: "@QQiRecordappBundle/Resources/config/routing.yml"
