Public.enlace:
    type: entity
    table: public.enlace
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        titulo:
            type: string
            length: 255
            fixed: false
            nullable: false
        url:
            type: string
            length: 255
            fixed: false
            nullable: false
        fecha:
            type: datetime
            nullable: false
        estado:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
