Public.lugar:
    type: entity
    table: public.lugar
    fields:
        idLugar:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_lugar
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 100
            fixed: false
            nullable: true
        cupo:
            type: integer
            unsigned: false
            nullable: true
    manyToOne:
        idTipoLugar:
            targetEntity: Tipolugar
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_tipo_lugar:
                    referencedColumnName: id_tipo_lugar
            orphanRemoval: false
        idFacultad:
            targetEntity: Facultad
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_facultad:
                    referencedColumnName: id_facultad
            orphanRemoval: false
    lifecycleCallbacks: {  }
