Public.estados:
    type: entity
    table: public.estados
    fields:
        idEstado:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_estado
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 30
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
