Public.rol:
    type: entity
    table: public.rol
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 255
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
