Public.horarioasignatura:
    type: entity
    table: public.horarioasignatura
    fields:
        idHAsig:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_h_asig
            generator:
                strategy: SEQUENCE
        correlativo:
            type: decimal
            nullable: false
    manyToOne:
        idAsignatura:
            targetEntity: Asignatura
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_asignatura:
                    referencedColumnName: id_asignatura
            orphanRemoval: false
        idHorario:
            targetEntity: Horario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_horario:
                    referencedColumnName: id_horario
            orphanRemoval: false
    lifecycleCallbacks: {  }
