Public.diahora:
    type: entity
    table: public.diahora
    fields:
        idDiahora:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_diahora
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 20
            fixed: false
            nullable: true
        dia:
            type: integer
            unsigned: false
            nullable: true
        hora:
            type: time
            nullable: true
    manyToOne:
        idCiclo:
            targetEntity: Ciclo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_ciclo:
                    referencedColumnName: id_ciclo
            orphanRemoval: false
    lifecycleCallbacks: {  }
