Public.escuelas:
    type: entity
    table: public.escuelas
    fields:
        idEscuela:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_escuela
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 150
            fixed: false
            nullable: true
    manyToOne:
        idFacultad:
            targetEntity: Facultad
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_facultad:
                    referencedColumnName: id_facultad
            orphanRemoval: false
    lifecycleCallbacks: {  }
