Public.horario:
    type: entity
    table: public.horario
    fields:
        idHorario:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_horario
            generator:
                strategy: SEQUENCE
        fechaCreacion:
            type: date
            nullable: true
            column: fecha_creacion
    manyToOne:
        idCarrera:
            targetEntity: Carrera
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_carrera:
                    referencedColumnName: id_carrera
            orphanRemoval: false
        idUsuario:
            targetEntity: Usuario
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
        idCiclo:
            targetEntity: Ciclo
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_ciclo:
                    referencedColumnName: id_ciclo
            orphanRemoval: false
        idEstado:
            targetEntity: Estados
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_estado:
                    referencedColumnName: id_estado
            orphanRemoval: false
    lifecycleCallbacks: {  }
