Public.tipoactividad:
    type: entity
    table: public.tipoactividad
    fields:
        idTipoActividad:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_tipo_actividad
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
