Public.asignatura:
    type: entity
    table: public.asignatura
    fields:
        idAsignatura:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_asignatura
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 50
            fixed: false
            nullable: false
        codigo:
            type: string
            length: 20
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
