Public.facultad:
    type: entity
    table: public.facultad
    fields:
        idFacultad:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_facultad
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
