Public.usuario:
    type: entity
    table: public.usuario
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 255
            fixed: false
            nullable: false
        apellido:
            type: string
            length: 255
            fixed: false
            nullable: false
        email:
            type: string
            length: 255
            fixed: false
            nullable: false
        password:
            type: string
            length: 255
            fixed: false
            nullable: false
        activo:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
