Public.tipolugar:
    type: entity
    table: public.tipolugar
    fields:
        idTipoLugar:
            id: true
            type: integer
            unsigned: false
            nullable: false
            column: id_tipo_lugar
            generator:
                strategy: SEQUENCE
        nombre:
            type: string
            length: 100
            fixed: false
            nullable: false
    lifecycleCallbacks: {  }
